server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678
springdoc:
  api-docs:
    path: /api-docs
olcp:
  jwt:
    tokenHeader: X-Token
    tokenHead: Bearer
    secret: ocl-secret
    expiration: 604800