server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:10301/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    enable-cluster: true
    cluster:
#      master1:
#        url: jdbc:mysql://127.0.0.1:10301/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: root
#        driver-class-name: com.mysql.cj.jdbc.Driver
      slave1:
        url: jdbc:mysql://127.0.0.1:10302/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: olcp-single
olcp:
  app-id: all