server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: olcp-single
olcp:
  app-id: all