server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  group-configs:
    - group: ALL
      paths-to-match: /**
  pre-loading-enabled: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/olcp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true