spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        physical-strategy: top.jiangliuhong.olcp.common.handler.DatabaseNamingStrategy
      ddl-auto: none
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  group-configs:
    - group: ALL
      paths-to-match: /**
  pre-loading-enabled: false